// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }

// app/layout.tsx
import "./globals.css";
export const metadata = { title: "Peminjaman Alat" };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="id">
      <body>
        <div className="min-h-screen bg-gray-50">
          <nav className="bg-white border-b p-4">
            <div className="container mx-auto flex items-center gap-4">
              <a href="/" className="font-bold">
                LabLoan
              </a>
              <a href="/peminjaman" className="ml-4 text-sm">
                Peminjaman
              </a>
              <a href="/manajemen" className="ml-4 text-sm">
                Manajemen
              </a>
              <a href="/riwayat" className="ml-4 text-sm">
                Riwayat
              </a>
            </div>
          </nav>
          <main className="container mx-auto p-4">{children}</main>
        </div>
      </body>
    </html>
  );
}
